language: cpp
sudo: true

matrix:
  include:
    - os: linux
      compiler: gcc
      addons: &gcc7
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env: COMPILER='g++-7' BUILD_TYPE='Release'

    - os: linux
      compiler: gcc
      addons: *gcc7
      env: COMPILER='g++-7' BUILD_TYPE='Debug'

before_install:
#  - sudo apt-get install -y libsfml-dev
# trying to use default libsfml-dev is not latest version (2.4.2)
# manually download and ensure all dependencies are built
  - sudo apt-get install -y freeglut3-dev 
  - sudo apt-get install -y libjpeg-dev 
  - sudo apt-get install -y libfreetype6-dev 
  - sudo apt-get install -y libxrandr-dev 
  - sudo apt-get install -y libglew-dev 
  - sudo apt-get install -y libsndfile1-dev 
  - sudo apt-get install -y libopenal-dev

install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.8/cmake-3.8.0-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
      SFML_URL="https://www.sfml-dev.org/files/SFML-2.4.2-linux-gcc-64-bit.tar.gz"
      mkdir sfml && travis_retry wget --no-check-certificate --quiet -O - ${SFML_URL} | tar --strip-components=1 -xz -C sfml
      export SFML_ROOT=${DEPS_DIR}/sfml
    fi

before_script:
  - export CXX=${COMPILER}
  - cd ${TRAVIS_BUILD_DIR}
  - cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
  - cd build

script:
  - make
